name: Test urdf_geometry_parser
on:
  pull_request:
  push:
    branches:
      - kinetic-devel
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic, ROS_REPO: main}
          - {ROS_DISTRO: kinetic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
    steps:
      - run: sudo apt-get update -qq && sudo apt-get upgrade
      - uses: actions/checkout@v1
      - uses: ros-industrial/industrial_ci@master
        env: ${{matrix.env}}
